import React, { useEffect, useState } from 'react';
import { Calendar, Clock, ArrowRight, Bookmark, ExternalLink, X } from 'lucide-react';

type SiteContentItem = {
    title: string;
    category: string;
    url: string;
    filename: string;
    sizeBytes: number;
    updatedAt: string;
};

type SiteContentManifest = {
    generatedAt: string;
    items: SiteContentItem[];
};

type BlogPost = {
    id: string;
    title: string;
    excerpt: string;
    date: string;
    readTime: string;
    category: string;
    image: string;
    url: string;
    index: number;
};

const contentImage = 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=800';

const formatDate = (value: string) => {
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return 'Local content';
    return date.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
};

const formatSize = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
    return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
};

const escapeHtml = (value: string) =>
    value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');

const markdownToHtml = (markdown: string) => {
    const lines = markdown.split(/\r?\n/);
    const html: string[] = [];
    let inList = false;

    const closeList = () => {
        if (inList) {
            html.push('</ul>');
            inList = false;
        }
    };

    for (const rawLine of lines) {
        const line = rawLine.trim();
        if (!line) {
            closeList();
            continue;
        }

        if (line.startsWith('### ')) {
            closeList();
            html.push(`<h3>${escapeHtml(line.slice(4))}</h3>`);
        } else if (line.startsWith('## ')) {
            closeList();
            html.push(`<h2>${escapeHtml(line.slice(3))}</h2>`);
        } else if (line.startsWith('# ')) {
            closeList();
            html.push(`<h1>${escapeHtml(line.slice(2))}</h1>`);
        } else if (line.startsWith('- ') || line.startsWith('* ')) {
            if (!inList) {
                html.push('<ul>');
                inList = true;
            }
            html.push(`<li>${escapeHtml(line.slice(2))}</li>`);
        } else {
            closeList();
            html.push(`<p>${escapeHtml(line)}</p>`);
        }
    }

    closeList();
    return html.join('\n');
};

export const Blog: React.FC = () => {
    const [contentItems, setContentItems] = useState<SiteContentItem[]>([]);
    const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);
    const [readerHtml, setReaderHtml] = useState('');
    const [readerLoading, setReaderLoading] = useState(false);

    useEffect(() => {
        let cancelled = false;

        fetch('/content/site-content.json', { cache: 'no-store' })
            .then((response) => response.ok ? response.json() : Promise.reject(new Error('No local content manifest')))
            .then((manifest: SiteContentManifest) => {
                if (!cancelled) setContentItems(manifest.items ?? []);
            })
            .catch(() => {
                if (!cancelled) setContentItems([]);
            });

        return () => {
            cancelled = true;
        };
    }, []);

    useEffect(() => {
        if (!selectedPost || selectedPost.url === '#') {
            setReaderHtml('');
            return;
        }

        const lowerUrl = selectedPost.url.toLowerCase();
        if (lowerUrl.endsWith('.html') || lowerUrl.endsWith('.htm')) {
            setReaderHtml('');
            return;
        }

        let cancelled = false;
        setReaderLoading(true);

        fetch(selectedPost.url, { cache: 'no-store' })
            .then((response) => response.ok ? response.text() : Promise.reject(new Error('Unable to load file')))
            .then((text) => {
                if (!cancelled) setReaderHtml(markdownToHtml(text));
            })
            .catch(() => {
                if (!cancelled) setReaderHtml('<p>Unable to load this file in the reader.</p>');
            })
            .finally(() => {
                if (!cancelled) setReaderLoading(false);
            });

        return () => {
            cancelled = true;
        };
    }, [selectedPost]);

    const posts: BlogPost[] = contentItems.map((item, index) => ({
        id: `local-${item.url}`,
        title: item.title,
        excerpt: `${item.filename} generated by autocontent. File size: ${formatSize(item.sizeBytes)}.`,
        date: formatDate(item.updatedAt),
        readTime: item.category,
        category: item.category,
        image: contentImage,
        url: item.url,
        index,
    }));

    if (selectedPost) {
        const lowerUrl = selectedPost.url.toLowerCase();
        const isHtml = lowerUrl.endsWith('.html') || lowerUrl.endsWith('.htm');

        return (
            <div className="pb-12 animate-[fadeIn_0.5s_ease-out_forwards]">
                <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                    <div>
                        <button
                            onClick={() => setSelectedPost(null)}
                            className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 mb-4"
                        >
                            <X className="w-4 h-4" /> Close Reader
                        </button>
                        <div className="flex items-center gap-3 text-xs font-semibold uppercase tracking-wider text-indigo-500 mb-3">
                            <span>{selectedPost.category}</span>
                            <span className="h-1 w-1 rounded-full bg-gray-300"></span>
                            <span>{selectedPost.date}</span>
                        </div>
                        <h1 className="text-3xl md:text-5xl font-bold tracking-tight text-gray-900 dark:text-white max-w-4xl">
                            {selectedPost.title}
                        </h1>
                    </div>
                    <a
                        href={selectedPost.url}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center justify-center gap-2 rounded-lg border border-gray-200 dark:border-dark-border px-4 py-2 text-sm font-semibold text-gray-700 dark:text-gray-200 hover:border-indigo-500 hover:text-indigo-500"
                    >
                        Raw File <ExternalLink className="w-4 h-4" />
                    </a>
                </div>

                <div className="bg-white dark:bg-dark-card border border-gray-200 dark:border-dark-border rounded-xl overflow-hidden shadow-xl">
                    {isHtml ? (
                        <iframe
                            src={selectedPost.url}
                            title={selectedPost.title}
                            className="w-full h-[78vh] bg-white"
                        />
                    ) : (
                        <article
                            className="max-w-4xl mx-auto px-6 py-10 md:px-10 md:py-14 text-gray-700 dark:text-gray-300 leading-8
                            [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:text-gray-900 [&_h1]:dark:text-white [&_h1]:mb-6
                            [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:text-gray-900 [&_h2]:dark:text-white [&_h2]:mt-10 [&_h2]:mb-4
                            [&_h3]:text-xl [&_h3]:font-semibold [&_h3]:text-gray-900 [&_h3]:dark:text-white [&_h3]:mt-8 [&_h3]:mb-3
                            [&_p]:mb-5 [&_ul]:mb-6 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mb-2"
                            dangerouslySetInnerHTML={{ __html: readerLoading ? '<p>Loading article...</p>' : readerHtml }}
                        />
                    )}
                </div>

                <style>{`
                    @keyframes fadeIn {
                        from { opacity: 0; transform: translateY(20px); }
                        to { opacity: 1; transform: translateY(0); }
                    }
                `}</style>
            </div>
        );
    }

    return (
        <div className="space-y-12 pb-12 animate-[fadeIn_0.5s_ease-out_forwards]">
            <div className="text-center max-w-2xl mx-auto space-y-4 pt-8">
                <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-gray-900 dark:text-white">
                    Published <span className="text-indigo-500">Content</span>
                </h1>
                <p className="text-lg text-gray-600 dark:text-gray-400">
                    Articles and files generated by autocontent, presented inside your website.
                </p>
            </div>

            <div className="flex flex-wrap justify-center gap-2">
                {['All', 'Article', 'Markdown', 'Video', 'Audio', 'Image', 'PDF'].map((tag, i) => (
                    <button
                        key={tag}
                        className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${
                            i === 0
                                ? 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/25'
                                : 'bg-white dark:bg-dark-card border border-gray-200 dark:border-dark-border text-gray-600 dark:text-gray-300 hover:border-indigo-500 hover:text-indigo-500'
                        }`}
                    >
                        {tag}
                    </button>
                ))}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {posts.map((post) => (
                    <div
                        key={post.id}
                        className="group bg-white dark:bg-dark-card rounded-2xl overflow-hidden border border-gray-200 dark:border-dark-border hover:shadow-xl hover:border-indigo-500/30 transition-all duration-300 flex flex-col h-full opacity-0 animate-[fadeIn_0.5s_ease-out_forwards]"
                        style={{ animationDelay: `${post.index * 100}ms` }}
                    >
                        <div className="relative h-52 overflow-hidden">
                            <img
                                src={post.image}
                                alt={post.title}
                                className="w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-500"
                            />
                            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-60"></div>
                            <div className="absolute top-4 left-4 bg-white/90 dark:bg-black/80 backdrop-blur-sm px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 border border-gray-200 dark:border-dark-border shadow-sm">
                                {post.category}
                            </div>
                        </div>
                        <div className="p-6 flex flex-col flex-1">
                            <div className="flex items-center gap-4 text-xs text-gray-500 dark:text-gray-400 mb-3">
                                <span className="flex items-center gap-1.5"><Calendar className="w-3.5 h-3.5" /> {post.date}</span>
                                <span className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" /> {post.readTime}</span>
                            </div>
                            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-indigo-500 transition-colors line-clamp-2">
                                {post.title}
                            </h3>
                            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed mb-6 flex-1 line-clamp-3">
                                {post.excerpt}
                            </p>
                            <div className="flex items-center justify-between mt-auto pt-4 border-t border-gray-100 dark:border-dark-border">
                                <button
                                    onClick={() => setSelectedPost(post)}
                                    className="inline-flex items-center text-sm font-semibold text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 transition-colors gap-1 group/link"
                                >
                                    Read Article <ArrowRight className="w-4 h-4 transform group-hover/link:translate-x-1 transition-transform" />
                                </button>
                                <button className="text-gray-400 hover:text-indigo-500 transition-colors" aria-label="Bookmark">
                                    <Bookmark className="w-4 h-4" />
                                </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {posts.length === 0 && (
                <div className="text-center border border-dashed border-gray-300 dark:border-dark-border rounded-xl p-10">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">No generated content yet</h3>
                    <p className="text-gray-600 dark:text-gray-400">Publish from autocontent, then refresh this page.</p>
                </div>
            )}

            <style>{`
                @keyframes fadeIn {
                    from { opacity: 0; transform: translateY(20px); }
                    to { opacity: 1; transform: translateY(0); }
                }
            `}</style>
        </div>
    );
};
